version: '3.8'
services:
  backend:
    image: backend-image
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: frontend-image
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
