version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
